### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nickabs** [nickabs/transmission#21]
#Transmission theme To-Do list
 
##  support for standard ghost features
- [ ] 
- [ ] Set up project structure
- [ ] Initialise Git

## improvements
- [ ] Implement user authentication
  - [x] Design login page
  - [ ] Backend integration
- [ ] Develop user profile page
  - [x] Profile UI design
  - [ ] Fetch user data from API

## Milestone 3: Testing and Deployment
- [ ] Write unit tests
- [ ] Perform integration tests
- [ ] Set up CI/CD pipeline
  - [ ] Configure GitHub Actions
  - [ ] Deploy to staging environment
- [ ] Deploy to production
Steps to Create the List:

**Comment by ngeorger** [comment]
Which kind of i18n are you looking for? Count on me for Spanish (Chile and Latin America)

**Comment by nickabs** [comment]
> Which kind of i18n are you looking for? Count on me for Spanish (Chile and Latin America)

I am going to try and reuse as many of the strings/languages from the ghost portal translations as possible, but help with any left over strings will be appreciated!

**Comment by nickabs** [comment]
i18n now supported (see v 2.11)

**Comment by chris2fr** [comment]
Is this Ghost 6.0 compatible ?
